### PR TITLE
Block multiple trackers from each source

### PR DESCRIPTION
**Pull request by danieldickison**
Replace all matches for a tracker regex so multiple trackers can be blocked.

This is untested as I couldn’t get Mail.app to enable my local build (probably due to lack of notorization?) Let me know if you have any tips on installing the plugin locally.

This implementation assumes that `stringByReplacingMatchesInString` returns the original string when no changes are made, to allow for an efficient `replaced != result` comparison rather than `isEqualToString`.

### CODE REVIEW

**Comment by apparition47** [comment]
>stringByReplacingMatchesInString returns the original string

This seems to be true, however with this PR, the tracker seems to attribute all my emails as coming from `Mailgun`.

**Comment by danieldickison** [comment]
Actually it seems that `stringByReplacingMatchesInString` does return a new string instance, as an NSMutableString. I've updated it to use `isEqualToString` to avoid the false positives. Also:
* I added unit tests of the sanitized html
* Check the generic tracking pixel regex after the others so that we're not dependent on the non-deterministic NSDictionary iteration order. Previously, if kGenericSpyPixel came up before one of the known trackers, it would remove the img tag completely and we wouldn't match the subsequent regexes.

**Comment by apparition47** [comment]
Thanks, this is great. I'll get around to testing it more this week. Been busy working through the mess of compatibility issues everyone has been bringing up this weekend.

Also, I haven't actually come across a vendor putting put multiple trackers in a single email yet. Does such a case exist?

**Comment by danieldickison** [comment]
> Also, I haven't actually come across a vendor putting put multiple trackers in a single email yet. Does such a case exist?

I haven't looked for actual cases, but I figure it's at least possible. However, since the `kGenericSpyPixelRegex` replacement ends up removing any repeats, it's not really necessary for that initial scan to replace all of the matches. I changed that part of the code back to what you had originally for simplicity and efficiency.

**Review by aaoyo — APPROVED** [review]

**Comment by apparition47** [comment]
Thanks for your submission. Looks great.

**Pull request merged**
